import { RoleModel } from './role.model';

const ROLES_WITH_PERMISSIONS: Record<string, string[]> = {
  USER: [
    'view_products',
    'view_product_details',
    'search_products',
    'add_to_cart',
    'update_cart',
    'remove_from_cart',
    'place_order',
    'view_own_orders',
    'cancel_own_order',
    'return_order',
    'make_payment',
    'view_payments',
    'download_invoice',
    'manage_own_profile',
    'update_own_profile',
    'manage_addresses',
    'write_review',
    'edit_own_review',
    'delete_own_review',
    'apply_coupon',
    'use_wallet',
    'contact_support',
  ],
  SELLER: [
    'view_seller_dashboard',
    'create_product',
    'update_own_product',
    'delete_own_product',
    'view_own_products',
    'manage_inventory',
    'update_stock',
    'view_own_orders',
    'update_own_order_status',
    'print_shipping_label',
    'generate_invoice',
    'manage_returns',
    'respond_to_customer_query',
    'view_sales_report',
    'view_settlement_report',
    'manage_store_profile',
    'update_bank_details',
  ],
  ADMIN: [
    'view_admin_dashboard',
    'manage_users',
    'block_user',
    'assign_roles',
    'manage_sellers',
    'approve_seller',
    'suspend_seller',
    'manage_all_products',
    'approve_product',
    'remove_product',
    'manage_all_orders',
    'update_any_order_status',
    'process_refund',
    'manage_categories',
    'manage_brands',
    'manage_attributes',
    'manage_coupons',
    'manage_discounts',
    'manage_offers',
    'view_reports',
    'view_financial_reports',
    'view_tax_reports',
    'manage_content',
    'manage_banners',
    'manage_pages',
    'manage_settings',
    'manage_notifications',
  ],
  SUPER_ADMIN: [
    'view_admin_dashboard',
    'manage_users',
    'block_user',
    'assign_roles',
    'manage_sellers',
    'approve_seller',
    'suspend_seller',
    'manage_all_products',
    'approve_product',
    'remove_product',
    'manage_all_orders',
    'update_any_order_status',
    'process_refund',
    'manage_categories',
    'manage_brands',
    'manage_attributes',
    'manage_coupons',
    'manage_discounts',
    'manage_offers',
    'view_reports',
    'view_financial_reports',
    'view_tax_reports',
    'manage_content',
    'manage_banners',
    'manage_pages',
    'manage_settings',
    'manage_notifications',
    'manage_admins',
    'manage_permissions',
    'system_config',
    'view_audit_logs',
    'emergency_access',
  ],
};

/**
 * Inserts default roles (USER, SELLER, ADMIN, SUPER_ADMIN) with their permissions
 * into the roles collection if they do not exist.
 * Idempotent: safe to run on every startup.
 */
export async function seedRoles(): Promise<void> {
  for (const [name, permissions] of Object.entries(ROLES_WITH_PERMISSIONS)) {
    await RoleModel.findOneAndUpdate(
      { name },
      { name, permissions },
      { upsert: true, new: true }
    );
  }
}
